# Generated by Django 5.1.7 on 2025-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="idd",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
